require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - ui/node_modules/**/*
    - bin/*
    - vendor/**/*
    - lib/generators/motor/templates/**/*
    - motor-admin.gemspec
  TargetRubyVersion: '2.6'

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'
    - spec/**/*
    - config/routes.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 20

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/ModuleLength:
  Max: 300

Style/ClassEqualityComparison:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/Capybara/VisibilityMatcher:
  Enabled: false

Metrics/ParameterLists:
  Max: 7
